### ISSUE TITLE
blindscan modules don't build in zeus

### ISSUE THREAD

**Issue by WanWizard** [neo-pli-bsps/meta-miraclebox#1]
````
mbmicro-build-image:2020-05-21 10:53:07 ERROR: miraclebox-blindscan-utils-mbmicro-1.0-r1 do_package_qa: QA Issue: /usr/bin/ceryon-tda1002x contained in package miraclebox-blindscan-dvbc-utils-mbmicro requires libxml2.so.2, but no providers found in RDEPENDS_miraclebox-blindscan-dvbc-utils-mbmicro? [file-rdeps]
````
this happens for the Micro, the Micro v2 and the Twin+.

All three need an RDEPENDS for "libxml2".

**Comment by WanWizard** [comment]
It looks like none of the patches in OpenPLi/meta-miraclebox where taken over?

**Comment by neo-pli-bsps** [comment]
I see it, sorry. It looks like I made the same mistake in some others too.

These issues should be fixed now, sorry.
